[build]
target = "i686-cascadeos.json"

[unstable]
build-std-features = ["compiler-builtins-mem"]  # enable normally disabled memory related functions
build-std = ["core", "compiler_builtins"]

[target.'cfg(target_os = "none")']
runner = "bash run.sh"